/*  C code generated by apiwrapper for GAMS Version 25.1.2
 *  Copyright (c) 2016, GAMS Development Corp.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <ctype.h>
#include <errno.h>

#define C4U_MAIN
#include "c4umcc.h"

#if defined(_WIN32)
# include <windows.h>
  static char winErr[] = "Windows error";
  typedef HINSTANCE soHandle_t;
#else
# include <unistd.h>
# include <dlfcn.h>
# include <sys/utsname.h>
  typedef void *soHandle_t;
#endif

static soHandle_t h;
static int isLoaded = 0;
static int objectCount = 0;
static int ScreenIndicator = 1;
static int ExceptionIndicator = 0;
static int ExitIndicator = 1;
static c4uErrorCallback_t ErrorCallBack = NULL;
static int APIErrorCount = 0;

#if defined(HAVE_MUTEX)
#include "gcmt.h"
static GC_mutex_t libMutex;
static GC_mutex_t objMutex;
static GC_mutex_t exceptMutex;

static int MutexIsInitialized = 0;

void c4uInitMutexes(void)
{
  int rc;
  if (0==MutexIsInitialized) {
    rc = GC_mutex_init (&libMutex);     if(0!=rc) c4uErrorHandling("Problem initializing libMutex");
    rc = GC_mutex_init (&objMutex);     if(0!=rc) c4uErrorHandling("Problem initializing objMutex");
    rc = GC_mutex_init (&exceptMutex);  if(0!=rc) c4uErrorHandling("Problem initializing exceptMutex");
    MutexIsInitialized = 1;
  }
}

void c4uFiniMutexes(void)
{
  if (1==MutexIsInitialized) {
    GC_mutex_delete (&libMutex);
    GC_mutex_delete (&objMutex);
    GC_mutex_delete (&exceptMutex);
    MutexIsInitialized = 0;
  }
}
#  define lock(MUTEX)   if(MutexIsInitialized) GC_mutex_lock (&MUTEX);
#  define unlock(MUTEX) if(MutexIsInitialized) GC_mutex_unlock (&MUTEX);
#else
#  define lock(MUTEX)   ;
#  define unlock(MUTEX) ;
void c4uInitMutexes(void) {}
void c4uFiniMutexes(void) {}
#endif

#if !defined(GAMS_UNUSED)
#define GAMS_UNUSED(x) (void)x;
#endif

typedef void (C4U_CALLCONV *c4uXCreate_t) (c4uHandle_t *pc4u);
static C4U_FUNCPTR(c4uXCreate);
typedef void (C4U_CALLCONV *c4uXFree_t)   (c4uHandle_t *pc4u);
static C4U_FUNCPTR(c4uXFree);
typedef int (C4U_CALLCONV *c4uXAPIVersion_t) (int api, char *msg, int *cl);
static C4U_FUNCPTR(c4uXAPIVersion);
typedef int (C4U_CALLCONV *c4uXCheck_t) (const char *ep, int nargs, int s[], char *msg);
static C4U_FUNCPTR(c4uXCheck);

#define printNoReturn(f,nargs) { \
  char d_msgBuf[256]; \
  strcpy(d_msgBuf,#f " could not be loaded: "); \
  c4uXCheck(#f,nargs,d_s,d_msgBuf+strlen(d_msgBuf)); \
  c4uErrorHandling(d_msgBuf); \
}
#define printAndReturn(f,nargs,rtype) { \
  char d_msgBuf[256]; \
  strcpy(d_msgBuf,#f " could not be loaded: "); \
  c4uXCheck(#f,nargs,d_s,d_msgBuf+strlen(d_msgBuf)); \
  c4uErrorHandling(d_msgBuf); \
  return (rtype) 0; \
}

void  C4U_CALLCONV d_c4uReadLice (c4uHandle_t pc4u, const char *syspath, const char *licefn, int WriteHTML)
{
  int d_s[]={0,11,11,15};
  GAMS_UNUSED(pc4u)
  GAMS_UNUSED(syspath)
  GAMS_UNUSED(licefn)
  GAMS_UNUSED(WriteHTML)
  printNoReturn(c4uReadLice,3)
}

int  C4U_CALLCONV d_c4uCheck4Update (c4uHandle_t pc4u)
{
  int d_s[]={15};
  GAMS_UNUSED(pc4u)
  printAndReturn(c4uCheck4Update,0,int )
}

int  C4U_CALLCONV d_c4uCheck4NewStudio (c4uHandle_t pc4u, int myStudio)
{
  int d_s[]={15,3};
  GAMS_UNUSED(pc4u)
  GAMS_UNUSED(myStudio)
  printAndReturn(c4uCheck4NewStudio,1,int )
}

void  C4U_CALLCONV d_c4uCreateMsg (c4uHandle_t pc4u)
{
  int d_s[]={0};
  GAMS_UNUSED(pc4u)
  printNoReturn(c4uCreateMsg,0)
}

void  C4U_CALLCONV d_c4uAddDistro (c4uHandle_t pc4u, const char *Distro)
{
  int d_s[]={0,11};
  GAMS_UNUSED(pc4u)
  GAMS_UNUSED(Distro)
  printNoReturn(c4uAddDistro,1)
}

void  C4U_CALLCONV d_c4uAddMsg (c4uHandle_t pc4u, const char *Msg, int pos)
{
  int d_s[]={0,11,3};
  GAMS_UNUSED(pc4u)
  GAMS_UNUSED(Msg)
  GAMS_UNUSED(pos)
  printNoReturn(c4uAddMsg,2)
}

int  C4U_CALLCONV d_c4uGetMsg (c4uHandle_t pc4u, int msgNr, char *Msg)
{
  int d_s[]={15,3,12};
  GAMS_UNUSED(pc4u)
  GAMS_UNUSED(msgNr)
  GAMS_UNUSED(Msg)
  printAndReturn(c4uGetMsg,2,int )
}

int  C4U_CALLCONV d_c4uIsValid (c4uHandle_t pc4u)
{
  int d_s[]={15};
  GAMS_UNUSED(pc4u)
  printAndReturn(c4uIsValid,0,int )
}

void * C4U_CALLCONV d_c4ugetMsgLst (c4uHandle_t pc4u)
{
  int d_s[]={1};
  GAMS_UNUSED(pc4u)
  printAndReturn(c4ugetMsgLst,0,void *)
}

int  C4U_CALLCONV d_c4uThisRel (c4uHandle_t pc4u)
{
  int d_s[]={3};
  GAMS_UNUSED(pc4u)
  printAndReturn(c4uThisRel,0,int )
}

char * C4U_CALLCONV d_c4uThisRelStr (c4uHandle_t pc4u, char *buf)
{
  int d_s[]={12};
  GAMS_UNUSED(pc4u)
  GAMS_UNUSED(buf)
  printAndReturn(c4uThisRelStr,0,char *)
}

int  C4U_CALLCONV d_c4uLastRel (c4uHandle_t pc4u)
{
  int d_s[]={3};
  GAMS_UNUSED(pc4u)
  printAndReturn(c4uLastRel,0,int )
}

char * C4U_CALLCONV d_c4uLastRelStr (c4uHandle_t pc4u, char *buf)
{
  int d_s[]={12};
  GAMS_UNUSED(pc4u)
  GAMS_UNUSED(buf)
  printAndReturn(c4uLastRelStr,0,char *)
}

int  C4U_CALLCONV d_c4uMsgCount (c4uHandle_t pc4u)
{
  int d_s[]={3};
  GAMS_UNUSED(pc4u)
  printAndReturn(c4uMsgCount,0,int )
}

/* return dirName on success, NULL on failure */
static char *
extractFileDirFileName (const char *fileName, char *dirName, char *fName)
{
  int fileNameLen, shave=0;
  const char *end, *s;
  char *t;

  if (NULL == fileName || NULL == dirName || fName == NULL) {
    return NULL;
  }
  fileNameLen = (int) strlen(fileName);

#if defined(_WIN32)
  /* get the last delimiter */
  for (end = fileName + fileNameLen - 1;
       end >= fileName && '\\' != *end && ':' != *end;  end--);
  /* shave off the trailing delimiter if:
   *  it isn't the first char,
   *  it is a backslash, and
   *  it is not preceded by a delimiter
   */
  if (end > fileName && '\\' == *end
   && (! ('\\' == *(end-1) || ':' == *(end-1)))
     ) {
    end--; shave=1;
  }
#else
  /* non-Windows: implicitly, this is the Unix version */
  /* get the last delimiter */
  for (end = fileName + fileNameLen - 1;
       end >= fileName && '/' != *end;  end--);

  if (end > fileName && '/' == *end) {
    end--; shave=1;
  }
#endif  /* if defined(_WIN32) */

  for (s = fileName, t = dirName;  s <= end;  s++, t++)
    *t = *s;
  *t = '\0';

  if (shave) s++;
  for (t = fName;  s <= fileName + fileNameLen - 1;  s++, t++)
    *t = *s;
  *t = '\0';

  return dirName;
} /* extractFileDirFileName */

static soHandle_t
loadLib (const char *libName, char **errMsg)
{
  soHandle_t h;

#if defined(_WIN32)
#if defined(UNICODE) || defined (_UNICODE)
  h = LoadLibraryA(libName);
#else
  h = LoadLibrary(libName);
#endif
  if (NULL == h) {
    *errMsg = winErr;
  }
  else {
    *errMsg = NULL;
  }
#else
  (void) dlerror();
  h = dlopen (libName, RTLD_NOW);
  if (NULL == h) {
    *errMsg = dlerror();
  }
  else {
    *errMsg = NULL;
  }
#endif

  return h;
} /* loadLib */

static int
unLoadLib (soHandle_t hh)
{
  int rc;

#if defined(_WIN32)
  rc = FreeLibrary (hh);
  return ! rc;
#else
  rc = dlclose (hh);
#endif
  return rc;
} /* unLoadLib */

static void *
loadSym (soHandle_t h, const char *sym, char **errMsg)
{
  void *s;
  const char *from;
  char *to;
  const char *tripSym;
  char lcbuf[257];
  char ucbuf[257];
  size_t symLen;
  int trip;

  /* search in this order:
   *  1. lower
   *  2. original
   *  3. upper
   */

  symLen = 0;
  for (trip = 1;  trip <= 3;  trip++) {
    switch (trip) {
    case 1:                             /* lower */
      for (from = sym, to = lcbuf;  *from;  from++, to++) {
        *to = tolower(*from);
      }
      symLen = from - sym;
      lcbuf[symLen] = '\0';
      tripSym = lcbuf;
      break;
    case 2:                             /* original */
      tripSym = sym;
      break;
    case 3:                             /* upper */
      for (from = sym, to = ucbuf;  *from;  from++, to++) {
        *to = toupper(*from);
      }
      ucbuf[symLen] = '\0';
      tripSym = ucbuf;
      break;
    default:
      tripSym = sym;
    } /* end switch */
#if defined(_WIN32)
#  if defined(HAVE_INTPTR_T)
    s = (void *)(intptr_t)GetProcAddress (h, tripSym);
#  else
    s = (void *)GetProcAddress (h, tripSym);
#  endif
    *errMsg = NULL;
    if (NULL != s) {
      return s;
    }
#else
    (void) dlerror();
    s = dlsym (h, tripSym);
    *errMsg = dlerror();
    if (NULL == *errMsg) {
      return s;
    }
#endif
  } /* end loop over symbol name variations */

  return NULL;
} /* loadSym */

/* TNAME = type name, ENAME = exported name */
#if defined(HAVE_INTPTR_T)
#  define LOADIT(TNAME,ENAME) symName = ENAME; TNAME = (TNAME##_t) (intptr_t) loadSym (h, symName, &errMsg); if (NULL == TNAME) goto symMissing
#  define LOADIT_ERR_OK(TNAME,ENAME) symName = ENAME; TNAME = (TNAME##_t) (intptr_t) loadSym (h, symName, &errMsg)
#else
#  define LOADIT(TNAME,ENAME) symName = ENAME; TNAME = (TNAME##_t) loadSym (h, symName, &errMsg); if (NULL == TNAME) goto symMissing
#  define LOADIT_ERR_OK(TNAME,ENAME) symName = ENAME; TNAME = (TNAME##_t) loadSym (h, symName, &errMsg)
#endif

#if ! defined(GMS_DLL_BASENAME)
# define GMS_DLL_BASENAME "joatdclib"
#endif
#if defined(_WIN32)
# if ! defined(GMS_DLL_PREFIX)
#  define GMS_DLL_PREFIX ""
# endif
# if ! defined(GMS_DLL_EXTENSION)
#  define GMS_DLL_EXTENSION ".dll"
# endif
# if ! defined(GMS_DLL_SUFFIX)
#  if defined(_WIN64)
#   define GMS_DLL_SUFFIX "64"
#  else
#   define GMS_DLL_SUFFIX ""
#  endif
# endif

#else  /* start non-Windows */

# if ! defined(GMS_DLL_PREFIX)
#  define GMS_DLL_PREFIX "lib"
# endif
# if ! defined(GMS_DLL_EXTENSION)
#  if defined(__APPLE__)
#   define GMS_DLL_EXTENSION ".dylib"
#  else
#   define GMS_DLL_EXTENSION ".so"
#  endif
# endif
# if ! defined(GMS_DLL_SUFFIX)
#  if defined(__WORDSIZE)
#   if 64 == __WORDSIZE
#    define GMS_DLL_SUFFIX "64"
#   else
#    define GMS_DLL_SUFFIX ""
#   endif
#  elif defined(__SIZEOF_POINTER__)
#   if 4 == __SIZEOF_POINTER__
#    define GMS_DLL_SUFFIX ""
#   elif 8 == __SIZEOF_POINTER__
#    define GMS_DLL_SUFFIX "64"
#   endif
#  elif defined(__sparcv9)
#   define GMS_DLL_SUFFIX "64"
#  elif defined(__sparc)
/*  check __sparc after __sparcv9, both are defined for 64-bit */
#   define GMS_DLL_SUFFIX ""
#  endif
# endif /* ! defined(GMS_DLL_SUFFIX) */
#endif

/* XLibraryLoad: return 0 on success, ~0 on failure */
static int
XLibraryLoad (const char *dllName, char *errBuf, int errBufSize)
{
  char *errMsg;
  const char *symName;
  int rc, cl;

  if (isLoaded)
    return 0;
  h = loadLib (dllName, &errMsg);
  if (NULL == h) {
    if (NULL != errBuf) {
      int elen;
      char* ebuf;
      elen = errBufSize;  ebuf = errBuf;
      rc = sprintf (ebuf, "%.*s", elen, "Could not load shared library ");
      elen -= rc;  ebuf+= rc;
      rc = sprintf (ebuf, "%.*s", elen, dllName);
      elen -= rc;  ebuf+= rc;
      rc = sprintf (ebuf, "%.*s", elen, ": ");
      elen -= rc;  ebuf+= rc;
      rc = sprintf (ebuf, "%.*s", elen, errMsg);
      /* elen -= rc;  ebuf+= rc; */
      errBuf[errBufSize-1] = '\0';
    }
    return 1;
  }
  else {
     /* printf ("Loaded shared library %s successfully\n", dllName); */
    if (errBuf && errBufSize)
      errBuf[0] = '\0';
  }

  LOADIT(c4uXCreate, "c4uXCreate");
  LOADIT(c4uXFree, "c4uXFree");
  LOADIT(c4uXCheck, "Cc4uXCheck");
  LOADIT(c4uXAPIVersion, "Cc4uXAPIVersion");

  if (!c4uXAPIVersion(2,errBuf,&cl))
    return 1;


#define CheckAndLoad(f,nargs,prefix) \
  if (!c4uXCheck(#f,nargs,s,errBuf)) \
    f = &d_##f; \
  else { \
    LOADIT(f,prefix #f); \
  }
  {int s[]={0,11,11,15}; CheckAndLoad(c4uReadLice,3,"C"); }
  {int s[]={15}; CheckAndLoad(c4uCheck4Update,0,""); }
  {int s[]={15,3}; CheckAndLoad(c4uCheck4NewStudio,1,""); }
  {int s[]={0}; CheckAndLoad(c4uCreateMsg,0,""); }
  {int s[]={0,11}; CheckAndLoad(c4uAddDistro,1,"C"); }
  {int s[]={0,11,3}; CheckAndLoad(c4uAddMsg,2,"C"); }
  {int s[]={15,3,12}; CheckAndLoad(c4uGetMsg,2,"C"); }
  {int s[]={15}; CheckAndLoad(c4uIsValid,0,""); }
  {int s[]={1}; CheckAndLoad(c4ugetMsgLst,0,""); }
  {int s[]={3}; CheckAndLoad(c4uThisRel,0,""); }
  {int s[]={12}; CheckAndLoad(c4uThisRelStr,0,"C"); }
  {int s[]={3}; CheckAndLoad(c4uLastRel,0,""); }
  {int s[]={12}; CheckAndLoad(c4uLastRelStr,0,"C"); }
  {int s[]={3}; CheckAndLoad(c4uMsgCount,0,""); }

 return 0;

 symMissing:
  if (errBuf && errBufSize>0) {
    int elen;
    char* ebuf;
    elen = errBufSize;  ebuf = errBuf;
    rc = sprintf (ebuf, "%.*s", elen, "Could not load symbol '");
    elen -= rc;  ebuf+= rc;
    rc = sprintf (ebuf, "%.*s", elen, symName);
    elen -= rc;  ebuf+= rc;
    rc = sprintf (ebuf, "%.*s", elen, "': ");
    elen -= rc;  ebuf+= rc;
    rc = sprintf (ebuf, "%.*s", elen, errMsg);
    /* elen -= rc;  ebuf+= rc; */
    errBuf[errBufSize-1] = '\0';
    /* printf ("%s\n", errBuf); */
    return 2;
  }

 return 0;

} /* XLibraryLoad */

static int
libloader(const char *dllPath, const char *dllName, char *msgBuf, int msgBufSize)
{

  char dllNameBuf[512];
  int myrc = 0;
  char gms_dll_suffix[4];

#if ! defined(GMS_DLL_PREFIX)
# error "GMS_DLL_PREFIX expected but not defined"
#endif
#if ! defined(GMS_DLL_BASENAME)
# error "GMS_DLL_BASENAME expected but not defined"
#endif
#if ! defined(GMS_DLL_EXTENSION)
# error "GMS_DLL_EXTENSION expected but not defined"
#endif
#if ! defined(GMS_DLL_SUFFIX)
# if defined (_WIN32)
#   error "GMS_DLL_SUFFIX expected but not defined"
# else
  struct utsname uts;

  myrc = uname(&uts);
  if (myrc) {
    strcpy(msgBuf,"Error, cannot define library name suffix");
    return 0;
  }
  if (0 == strcmp(uts.sysname, "AIX")) /* assume AIX is 64-bit */
    strcpy (gms_dll_suffix, "64");
  else if (0 == strcmp(uts.sysname, "Darwin")) {
    /* keep Darwin test in here: fat binaries must check at run time */
    if (8 == (int)sizeof(void *))
      strcpy (gms_dll_suffix, "64");
    else
      strcpy (gms_dll_suffix, "");
  }
  else {
    strcpy(msgBuf,"Error, cannot define library name suffix");
    return 0;
  }
# endif
#else
  strcpy (gms_dll_suffix, GMS_DLL_SUFFIX);
#endif


  if (NULL != msgBuf) msgBuf[0] = '\0';

  if (! isLoaded) {
    if (NULL != dllPath && '\0' != *dllPath) {
      strncpy(dllNameBuf, dllPath, sizeof(dllNameBuf)-1);
      dllNameBuf[sizeof(dllNameBuf)-1] = '\0';
#if defined(_WIN32)
      if ('\\' != dllNameBuf[strlen(dllNameBuf)])
        strcat(dllNameBuf,"\\");
#else
      if ('/' != dllNameBuf[strlen(dllNameBuf)])
        strcat(dllNameBuf,"/");
#endif
    }
    else {
      dllNameBuf[0] = '\0';
    }
    if (NULL != dllName && '\0' != *dllName) {
      strncat(dllNameBuf, dllName, sizeof(dllNameBuf)-strlen(dllNameBuf)-1);
    }
    else {
      strncat(dllNameBuf, GMS_DLL_PREFIX GMS_DLL_BASENAME, sizeof(dllNameBuf)-strlen(dllNameBuf)-1);
      strncat(dllNameBuf, gms_dll_suffix                 , sizeof(dllNameBuf)-strlen(dllNameBuf)-1);
      strncat(dllNameBuf, GMS_DLL_EXTENSION              , sizeof(dllNameBuf)-strlen(dllNameBuf)-1);
    }
    isLoaded = ! XLibraryLoad (dllNameBuf, msgBuf, msgBufSize);
    if (isLoaded) {
    }
    else {                              /* library load failed */
      myrc |= 1;
    }
  }
  return (myrc & 1) == 0;
}


/* c4uGetReady: return false on failure to load library, true on success */
int c4uGetReady (char *msgBuf, int msgBufSize)
{
  int rc;
  lock(libMutex);
  rc = libloader(NULL, NULL, msgBuf, msgBufSize);
  unlock(libMutex);
  return rc;
} /* c4uGetReady */

/* c4uGetReadyD: return false on failure to load library, true on success */
int c4uGetReadyD (const char *dirName, char *msgBuf, int msgBufSize)
{
  int rc;
  lock(libMutex);
  rc = libloader(dirName, NULL, msgBuf, msgBufSize);
  unlock(libMutex);
  return rc;
} /* c4uGetReadyD */

/* c4uGetReadyL: return false on failure to load library, true on success */
int c4uGetReadyL (const char *libName, char *msgBuf, int msgBufSize)
{
  char dirName[1024],fName[1024];
  int rc;
  extractFileDirFileName (libName, dirName, fName);
  lock(libMutex);
  rc = libloader(dirName, fName, msgBuf, msgBufSize);
  unlock(libMutex);
  return rc;
} /* c4uGetReadyL */

/* c4uCreate: return false on failure to load library, true on success */
int c4uCreate (c4uHandle_t *pc4u, char *msgBuf, int msgBufSize)
{
  int c4uIsReady;

  c4uIsReady = c4uGetReady (msgBuf, msgBufSize);
  if (! c4uIsReady) {
    return 0;
  }
  assert(c4uXCreate);
  c4uXCreate(pc4u);
  if(pc4u == NULL)
  { strcpy(msgBuf,"Error while creating object"); return 0; }
  lock(objMutex);
  objectCount++;
  unlock(objMutex);
  return 1;                     /* return true on successful library load */
} /* c4uCreate */

/* c4uCreateD: return false on failure to load library, true on success */
int c4uCreateD (c4uHandle_t *pc4u, const char *dirName,
                char *msgBuf, int msgBufSize)
{
  int c4uIsReady;

  c4uIsReady = c4uGetReadyD (dirName, msgBuf, msgBufSize);
  if (! c4uIsReady) {
    return 0;
  }
  assert(c4uXCreate);
  c4uXCreate(pc4u);
  if(pc4u == NULL)
  { strcpy(msgBuf,"Error while creating object"); return 0; }
  lock(objMutex);
  objectCount++;
  unlock(objMutex);
  return 1;                     /* return true on successful library load */
} /* c4uCreateD */

/* c4uCreateL: return false on failure to load library, true on success */
int c4uCreateL (c4uHandle_t *pc4u, const char *libName,
                char *msgBuf, int msgBufSize)
{
  int c4uIsReady;

  c4uIsReady = c4uGetReadyL (libName, msgBuf, msgBufSize);
  if (! c4uIsReady) {
    return 0;
  }
  assert(c4uXCreate);
  c4uXCreate(pc4u);
  if(pc4u == NULL)
  { strcpy(msgBuf,"Error while creating object"); return 0; }
  lock(objMutex);
  objectCount++;
  unlock(objMutex);
  return 1;                     /* return true on successful library load */
} /* c4uCreateL */

int c4uFree   (c4uHandle_t *pc4u)
{
  assert(c4uXFree);
  c4uXFree(pc4u); pc4u = NULL;
  lock(objMutex);
  objectCount--;
  unlock(objMutex);
  return 1;
} /* c4uFree */

int c4uLibraryLoaded(void)
{
  int rc;
  lock(libMutex);
  rc = isLoaded;
  unlock(libMutex);
  return rc;
} /* c4uLibraryLoaded */

int c4uLibraryUnload(void)
{
  lock(objMutex);
  if (objectCount > 0)
  {
    unlock(objMutex);
    return 0;
  }
  unlock(objMutex);
  lock(libMutex);
  isLoaded = 0;
  (void) unLoadLib(h);
  unlock(libMutex);
  return 1;
} /* c4uLibraryUnload */

int  c4uCorrectLibraryVersion(char *msgBuf, int msgBufLen)
{
  int cl;
  char localBuf[256];

  if (msgBuf && msgBufLen) msgBuf[0] = '\0';

  if (! isLoaded) {
    strncpy(msgBuf, "Library needs to be initialized first", msgBufLen);
    return 0;
  }

  if (NULL == c4uXAPIVersion) {
    strncpy(msgBuf, "Function c4uXAPIVersion not found", msgBufLen);
    return 0;
  }

  c4uXAPIVersion(C4UAPIVERSION,localBuf,&cl);
  strncpy(msgBuf, localBuf, msgBufLen);

  if (1 == cl)
    return 1;
  else
    return 0;
}

int c4uGetScreenIndicator(void)
{
  return ScreenIndicator;
}

void c4uSetScreenIndicator(int scrind)
{
  ScreenIndicator = scrind ? 1 : 0;
}

int c4uGetExceptionIndicator(void)
{
   return ExceptionIndicator;
}

void c4uSetExceptionIndicator(int excind)
{
  ExceptionIndicator = excind ? 1 : 0;
}

int c4uGetExitIndicator(void)
{
  return ExitIndicator;
}

void c4uSetExitIndicator(int extind)
{
  ExitIndicator = extind ? 1 : 0;
}

c4uErrorCallback_t c4uGetErrorCallback(void)
{
  return ErrorCallBack;
}

void c4uSetErrorCallback(c4uErrorCallback_t func)
{
  lock(exceptMutex);
  ErrorCallBack = func;
  unlock(exceptMutex);
}

int c4uGetAPIErrorCount(void)
{
  return APIErrorCount;
}

void c4uSetAPIErrorCount(int ecnt)
{
  APIErrorCount = ecnt;
}

void c4uErrorHandling(const char *msg)
{
  APIErrorCount++;
  if (ScreenIndicator) { printf("%s\n", msg); fflush(stdout); }
  lock(exceptMutex);
  if (ErrorCallBack)
    if (ErrorCallBack(APIErrorCount, msg)) { unlock(exceptMutex); exit(123); }
  unlock(exceptMutex);
  assert(!ExceptionIndicator);
  if (ExitIndicator) exit(123);
}

